### ISSUE TITLE
I find this linter counter productive.

### ISSUE THREAD

**Issue by arvenil** [mbilski/exhaustivestruct#2]
I understand it can be useful in certain cases, but most of the time it's counter productive. Zero values are encouraged by go, same is for field structs, I find it silly to define that member e.g. "Disabled" needs to be marked as false. I didn't put the value their, so I know it will use default, zero value.

```
linters:
  enable-all: true
  disable:
    - exhaustivestruct
```
